remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Joseph Louthan
description: Trying to waste my time with God. Preacher of the Gospel. Writing at Theologicus. StarCraft 2 Elderly.
show_downloads: "true"